// Firebase Configuration
#define FIREBASE_API_KEY "XXXXXXXX"
#define FIREBASE_PROJECT_ID "XXXXXXXX"
#define FIREBASE_DATABASE_URL "XXXXXXXX"
#define FIREBASE_USER_EMAIL "XXXXXXXX"
#define FIREBASE_USER_PASSWORD "XXXXXXXX"